### ISSUE TITLE
Credentials lost after a period of time

### ISSUE THREAD

**Issue by cdps82** [arvvoid/plugin.video.hbogoeu#139]
Hi, I have already contacted you somewhere else regarding the same problem. You have answered that the problem must be in my OS. Unfortunately I have tried to test it on 3 different devices (rpi2, rpi3, rpi3B+), and 2 different OS (OSMC, LibreELEC)  each. Your addon is always installed from the official repo in OS'. What I get is still the same issue. After the installation and loging in, I can watch movies, everything seems to be fine. But then after some time it asks for my credentials over and over again. Everything works back again when I re-login. But only until a certain moment when it all goes over again. I have thought about the idea of limitations coming from HBO GO servers. Not sure but if I remember well, 4 registered and 2 streaming devices at the same time. But that should be out of this issue. One single registered and streaming device is causing the same problem. I am registering via sledovanitv.cz provider using my e-mail and password credentials (if that's any important). All used OS and your addons were the latest Leia builds.

Thank you for your great job. Much appreciated, man.

**Comment by arvvoid** [comment]
Hello, and i reapet this most likely have nothing to do with the addon. 
You did’t follow the template for reporting and instructions, eveything is important nobody can guess whas going on on your decice/devices provide all requested info and a full debug log recreating the issue, perform a full setup then restar your device and provide an aditional log of what happen after the restart.

EDIT ADITION: RPI with OSMC or LibreELEC the add-on works fine normally the described problem doesn't happen. So only detailed logs of before and after can tell us whats going on in this case.

**Comment by cdps82** [comment]
Sorry for bothering, I have solved this issue by installing addon from Otava5 Fork which works just flawlessly. You can close this issue. 

BTW: It's definitely not related to RPI, OSMC or LibreELEC, but that specific type of login via sledovanitv.cz. I have tried to use my friend's UPC credentials which seemed fine for 48 hours. Has anyone already complained?

**Comment by arvvoid** [comment]
Hello @cdps82, you are not bothering but reporting an issue witch is more then welcome and you are encouraged to do so if finding any, and I would be happy to help and fix if I can, but to do that I need the reporter to provide all the required information and most importantly debug logs (and any additional info and/or logs it might be needed to get to the bottom of the issue). 
From the description alone in most cases, I can't do much, I can do a lot if provided with logs as requested.

There were no similar reports so far, and the mentioned operator uses the same login mechanism as most other operators. If where a problem with the login mechanism all operators sharing this login mechanism would probably be affected. So with the info I currently have it's unlikely the problem is with the operator but nothing is excluded, but without a log is impossible to know for sure. 
Full operator support list and login type for each pulled directly from the API: https://github.com/arvvoid/plugin.video.hbogoeu/wiki/Regional-support.
Without a full log, not having access to the said operator, I can't do much, with a log I can see exactly what is going on.

The only remotely similar reports is if the device id change then the add-on will re-ask just for username and password because if the device key changed for some reason will not be able to decrypt the credentials (the add-on provide some minimal credential protection by encrypting them using the device idI) for some unkown reason on some devices (but this happen rarely certainly not on daily basis at least it should not normally) the device id probably change. Witch is why I'm contemplating adding an option to disable the security feature for the very very rare situations where it causes problems.
But if you are affected by this or its something else entirely I can't possibly know without a log.

**_That's the reason why issues (bug reports) without logs and not properly compiled get generally discarded._**
Because without precise info it's just, a lot of time wasted in guessing, and possibly a lot of wrong directions taken, instead of using that energy to simply solve the problem.

To resolve this issue here:

OPTION A) Since you mention a fix for this issue (which is unknown at this time without a log) exist in a fork of this add-on a pull request can be sent, would be happy to review and include here.

OPTION B) A new clean issue can be opened while following the reporting template, a short and clear description and debug log (or multiple logs, in this case, would be more appropriate one while the credentials are working and one after they get lost), will lead probably to the speedy resolution of the issue.

Instruction to take a log quote from readme.md:

> PLEASE IF YOU ARE REPORTING AN ISSUE PROVIDE Kodi Debug Logs: https://kodi.wiki/view/Log_file/Easy . Without a full log is difficult or impossible to guess what's going on.

Locking because the conversation can be continued on the pull request or on a clean issue with logs provided if you are interested. Otherwise, the discussion is leading nowhere.
