### ISSUE TITLE
[BUG]  Can only play a few series with inject subtitles enabled (specific region only RO)

### ISSUE THREAD

**Issue by valerian-constantin** [arvvoid/plugin.video.hbogoeu#165]
Romanian here, from Orange TV Operator. I recently installed HGo EU and I have this annoying problem :c
I tried it on my laptop with Kodi, but also with Kodi on Android TV, happens on both.
I can play Kids TV Shows, but not movies. I also cannot play any other TV Shows or movies or documentaries. It just loads and eventually gives an error. It does not have anything to do with my account, as I can play just fine on HBO GO web on Chrome or Edge, but I really need this on Kodi.
Leia 18, latest stable on both devices.
Android 7.1 on Android TV, Windows 10 Latest stable on Laptop.
I attached a log from my laptop, trying to play Hercules, which just hangs then gives an error of playback.

I know I already made an issue and that I closed it, but it worked just for a second, now it doesn't work again anywhere, I don't know what to do, I can only play the Kids Series, no movies, no other movies or other TV shows.
[kodi_new.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/5067520/kodi_new.log)

I just get playback errors on all videos except kids tv series, I'm confused :c

**Comment by arvvoid** [comment]
Hello, the playback still works fine for all content in all my tests on all platforms I'm able to test on (LibreElec, Linux, Windows, MacOS). 
From your previous log there is nothing wrong add-on side. For the new log you don't have debugging turned on so nothing useful there.
If it worked after widevine re-instalation then there is most likely nothing wrong with the add-on the problem is elsewhere. 
Make sure something is not deleting or modifying the widevine file in cdm dir.
Before doing anything take a screenshot of the widevine info screen in Kodi, you can launch from add-on configuration DRM section, post. a screenshot here.

You have a banned repository present on your Kodi installation:
`2020-08-11 19:06:28.631 T:8232  NOTICE: ADDON: superrepo.kodi.jarvis.all v0.7.04 installed`

For further assistance, I suggest reinstalling a clean Kodi installation from the official site and don't install any repositories/add-ons of dubious origin and purpose.Then try again if the problem persists you can post a clean full debug log. Make sure you log just wat's relevant, turn debugging on, close Kodi. Start Kodi again, start playback of content from the add-on, try playing something that plays, and then something that fails to play and post a log.

PS. If someone else is experiencing the same problem confirmation here would be helpful. The add-on have a large userbase if there is a playback problems in general reports will start coming in soon.

**Comment by valerian-constantin** [comment]
Hey again! :)

Sorry for that repo, I did a clean install and the problem persists. I also tried Kodi in my phone and reinstalled it on Android TV, no luck. On the web it's all fine, no problems, but on Kodi it keeps loading indefinitely. I activated debug logging and I just opened Kodi and tried to play Hercules, not working again. I uninstalled widevine and tried again multiple times, still not working. I checked cdm directory, everything is fine, even cleared it and tried again, still not working.
![image](https://user-images.githubusercontent.com/69059759/90108129-806e7200-dd52-11ea-8f0e-86704cb12f82.png)
![image](https://user-images.githubusercontent.com/69059759/90108161-8b290700-dd52-11ea-8d66-c8f4ab901a10.png)
![image](https://user-images.githubusercontent.com/69059759/90110362-c24ce780-dd55-11ea-91e3-55fce2402848.png)

[kodi.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/5067801/kodi.log)

Also, I thought of attaching a log from a video that is working (gumball, because only kids series work):
[kodi_video that s working.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/5067874/kodi_video.that.s.working.log)


It hangs indefinitely so I just press esc to stop it so I can go back... 
Please tell me if you need anything else, sorry for the previous stuff. If you need my account for test purposes, I have no problem with it, I'd love to help, so you could replicate the issue :)

**Comment by arvvoid** [comment]
It's strange can't find anything meaningful in the log. Also in my tests all work fine with any content. All seams to work fine, but for the content that don't play the script hangs for no apparent reason in the moment things get passed to Kodi and inputstream.adaptive and then it gets killed off because of time-out.

There is some kind of inputstream.adaptive error but't don't think is relevant, if you changed inputstream adaptive settings try to set them to default.

Try to disable the inject subtitles option in the add-on config, don't think thats the issue, but just to be sure, if it's the same you can re-enable that.

**Comment by valerian-constantin** [comment]
oh my god!!!
I just disabled subtitles injection and it all seems to work well now. I'm trying to not get too excited, but I hope it will work now!! Just tested it on my Android TV and that seemed to be the problem, something with the subtitles I guess.
Thank you very much and sorry if I caused any trouble :)

**Comment by arvvoid** [comment]
ok, glad it worked, let me know if that fixed the issue, if yes will have to investigate what's going on with external subtitles in your region and see what's causing the problem.
Can't replicate the problem in my region the external subtitle processor still works fine here.

if inject subtitles is disabled the subtitles embedded in the stream will be used, but those are known to glitch sometimes and disappear during playback, they usually reaper a few minutes later or after rewinding a few seconds. But that might have been fixed.

**Comment by valerian-constantin** [comment]
Hey, that actually solved the problem, I'll let you know if there will be any subtitle glitching or anything. If you need any logs or any stuff, I'm here :)

UPDATE: With subtitle injecting disabled it works well, but subtitles sometimes dissappear for a minute or so, but they come back eventually.

**Comment by arvvoid** [comment]
This issue is stalled and there where no more reports might have been only a temporary issue. Closing can be reopened if someone experience the same problem.
