### ISSUE TITLE
 Does not play anything [unsupported old widevine version problem]

### ISSUE THREAD

**Issue by dquesado** [arvvoid/plugin.video.hbogoeu#167]
Hi
I’m from Portugal, using HBO go Portugal. I’ve just installed the add-on on my android TV box and everything is fine until I select something to watch. Then it tries to start the episode for a bit but does not go through with it.

I’ve seen another issue report where this happened in certain series and it was said to deselect “inject subtitles” but on my case it happens every time and deselecting “inject subtitles" did not fix it. I’ve tried with a lot of series, movies, kids shows and nothing opens.

My account on HBO Go works fine and I can see my shows on the continue watching but if I click on one to play it does not work.

Kodi version is Leia 18.8
Android TV box is Mecool M8s Pro L Android 7.1.2

[kodi.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/5169349/kodi.log)

Thanks

**Comment by arvvoid** [comment]
Hello, the problem might be something else entirely, inject subtitles don't cause any problem for most regions.

Unfortunately, the log you posted doesn't have debug enabled, please enable debug and post a new log.
If you just installed try also to restart the device and try to play something. Also, check the widevine version available on your device, does the official client work on your android device?

**Comment by dquesado** [comment]
Hi
Sorry about the log thing. I am not very familiar with these things.

Here is the new log, which I think has what you need:
[kodi(1).log](https://github.com/arvvoid/plugin.video.hbogoeu/files/5184523/kodi.1.log)

I have both re-installed kodi, re-installed the add-on and restarted the device. It is still not working.

Widevine info: 
![Screenshot_20200907-181911](https://user-images.githubusercontent.com/24228839/92411546-32c20b00-f140-11ea-9141-a4c82af377a6.png)

What do you mean with "does the official client work on your android device?" Are you asking if the HBO app works on my device? If so the answer is no. 

I install the app and it always gives me the error "Unable to connect to internet". I've contacted HBO and this is because they don't support my android TV box. That is why I’m trying this add-on. Netflix app works great though.

Thanks in advance for your time and patience.

**Comment by arvvoid** [comment]
From the log there is no error on the add-on side the error happens when widevine has to negotiate the key.

```
2020-09-07 18:04:29.390 T:11962   DEBUG: AddOnLog: InputStream Adaptive: WVDecrypter JNI, SDK version: 25, class: org/xbmc/kodi
2020-09-07 18:04:29.396 T:11962   DEBUG: AddOnLog: InputStream Adaptive: WVDecrypter constructed
2020-09-07 18:04:29.397 T:11962   ERROR: AddOnLog: InputStream Adaptive: Key system request: com.widevine.alpha
```

It looks like unfortunately the device used has a too old Widevine version included, Hbo Go EU requires a newer one. Unless there is a firmware update that includes a new widevine version there is no chance to get that working on that device.
If there is no firmware update (android update) that include a recent widevine version for the device, you can eventually try to boot coreelec on the device, I can't say if it's even bootable, and run the add-on from there. I can't provide support for that but you can find plenty of information on coreelec forums and eventually ask for help with installation on your device the community there.

PS. Netflix still works with both older and newer widevine versions, they might just give lower quality streams and don't allow HW decoding if some conditions are not met.
Every content provider has a different set of rules. Hbo Go EU don't have many restrictions at the moment and will usually always give 1080p HW decoded streams on all devices but require a newer widevine version, on regularly updated and still supported devices should not be an issue.

Recomandetion: First try to see if there is an official OS update for your device. If not you can try the Coreelec route if you don't need Android.

**Comment by dquesado** [comment]
Thanks. I'll try that
