### ISSUE TITLE
[BUG] Unable to load list of TV Series Friends in Czech language

### ISSUE THREAD

**Issue by CZJohny** [arvvoid/plugin.video.hbogoeu#194]
* [ ] Are you running the latest version?
YES Addon Hbo EU 2.7.1 (plugin.video.hbogoeu-2.7.1-matrix.zip)
Kodi Matrix 19.1

**Describe the bug**
Failed to load TV series Friends - get an error There is a newer version available, please update...  
Other series or Movies works fine, also can play directly from HBO official app in TV

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to TV Series
2. Click on Friends (Přátelé)
3. See an error (screenshot)

**Expected behaviour**
Load list of series 1-10

## Debug log - https://kodi.wiki/view/Log_file/Easy
[kodi.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/6575740/kodi.log)

[Please note, bug reports without full logs will be marked as ignored rules and ignored untill a log is provided]

**Screenshots**
![DSC_0263](https://user-images.githubusercontent.com/20719137/120313313-12436d80-c2da-11eb-9217-13ee16093068.JPG)

**Operating System**

* [* ] Android TV 7.0 (SONY TV)

**Additional informatin on the environment**

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

**Additional context**

**Comment by arvvoid** [comment]
Hello tnx for reporting.

There have been some api changes recently on hbo go side so might be related to that or might have been just  a temporary error on their side.
I watched the other day and tried now and it seams to work fine for me.

Go to settings and clear the add-on cache to force a new retrieval of data from the service now since the cache TTL is 24h and try again, to exclude it was just an temporary error on their side.

To clear the cache go to add-on settings -> expert -> clear request cache

![screenshot00001](https://user-images.githubusercontent.com/46710439/120322748-0ad59180-c2e5-11eb-9f65-22d2376de30f.png)

Let me know the outcome.

**Comment by CZJohny** [comment]
Thank you, clearing the request cache helped. :)
