### ISSUE TITLE
Cannot play any video streams: DecryptSampleData: Decrypt failed with error: 2 and key ...

### ISSUE THREAD

**Issue by doggopwn** [arvvoid/plugin.video.hbogoeu#200]
* [x] Are you running the latest version?

**Describe the bug**
Kodi crashes after a few seconds when trying to play anything.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start hGO EU from the Add-ons menu.
2. Select any movie or episode of choice.
3. Click on the title to start playing.
4. Observe Kodi crashing after a few seconds of loading

**Expected behaviour**
For the video to start playing normally.

## Debug log
[Link](https://paste.kodi.tv/ebinujasam.kodi)

**Screenshots**
N/A

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Additional information on the environment**
Running latest 19.1 Nightly (20210822-34a88a9059)

![image](https://user-images.githubusercontent.com/46420924/130668161-2398fc50-c228-41fd-93f6-14ac43ee1db3.png)

**Additional context**
Other DRM services like Netflix run just fine.

**Comment by doggopwn** [comment]
@arvvoid

**Comment by arvvoid** [comment]
Hello, the error is external to the add-on nothing I can fix on this end. Happens in inputstream.adaptive. 
I can't recreate the problem in Kodi 19.1 stable release and latest widevine version, al work fine for me.

**Comment by arvvoid** [comment]
@DoggoKt does it happen only on a specific movie/series?

**Comment by otava5** [comment]
Hello. Under Windows 10 it works, but under Coreelec 9.2.5 - Kodi 18.9 not even with the latest CDM library. Sending debug log
```
EDIT arvvoid: removed pasted log (please don't paste logs directly, upload as file or use a pastebin like site)
```

**Comment by arvvoid** [comment]
UPDATE on the issue. This is most likely because old widevine versions got revoked by google and can't be used anymore. So ARM devices (Android is not affected) to support new widevine versions an os update is needed. So you have to check on your OS forum if an os update supporting new widevine versions is available.

Nothing to do about this on the add-on side.

Take a read here: https://www.matthuisman.nz/2021/05/widevine-arm-broken.html , https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/437

But all other OS except ARM linux shoud be fine if inputstream.adaptive and latest widevine are installed.

**Comment by otava5** [comment]
Here is an update I’ve built for CoreELEC S905/S912 devices using the PR code above
This will get widevine working until they (hopefully) release 9.2.8

https://sourceforge.net/projects/coreelec/files/CoreELEC-Amlogic.arm-9.2-devel-1630714868.tar/download

Download that and do the “manual update” procedure.
I’ve tested in on my Odroid C2

_from **matthuisman**_

**Comment by razorxster** [comment]
Hi guys!

OSMC 19.1 also affected :(

**Comment by durip** [comment]
> Hi guys!
> 
> OSMC 19.1 also affected :(

working temporary fix for OSMC

https://github.com/xbmc/inputstream.adaptive/issues/678#issuecomment-913047151

**Comment by arvvoid** [comment]
Closing since there is nothing to do on the add-on side about this. The discussion and tips can continue on Kodi forum or Discussions section here: https://github.com/arvvoid/plugin.video.hbogoeu/discussions/207

The situation should be completely resolved when all arm linux distributions support new widevine versions.
