### ISSUE TITLE
[SUPPORT] No subtitles available

### ISSUE THREAD

**Issue by FunctionalHacker** [arvvoid/plugin.video.hbogoeu#210]
* [x] Are you running the latest version?

**Befor sending the support request this resources can be checked:**

[Kodi Forum thread](https://forum.kodi.tv/showthread.php?tid=339798) |
[Project wiki](https://github.com/arvvoid/plugin.video.hbogoeu/wiki) | 
[FAQ](https://github.com/arvvoid/plugin.video.hbogoeu/wiki/FAQ) | 
[Troubleshoot](https://github.com/arvvoid/plugin.video.hbogoeu/wiki/Troubleshoot)

* [x] I have already checked all resources above

* [ ] I just want to provide feedback or get in touch

**Please enter your question or feedback**

I can't get any subtitles using this addon. Kodi just says "no subtitles available". I'm using HBO Nordic in Finland and I have not changed any addon settings.

**Comment by VadVoci** [comment]
It is possible to configure the subtitle to be chosen automatically in a certain language 

I use Kodi 19 on Amazon FireTV gen 2 and plugin.video.hbogoeu arvvoid-2.7.8+matrix1

In player settings at language, prefered language subtitle, Romanian is chosed
"Download automaticaly the first subtitle" is ticked

The subtitle settings in the addon seem to have no effect. 

Every time I watch a movie, the English version of the subtitle is automatically chosen instead of the Romanian version.

**Comment by arvvoid** [comment]
Hello @FunctionalHacker the subtitles should work unless something changed on hbo side. Does the problem happen on all content or only specific content? Are subtitle available with the official client for the same content?

It would be best to open a bug report with logs recreating the issue otherwise is impossible to know what's going on.

**Comment by arvvoid** [comment]
@VadVoci this is a separate question unrelated to this issue. The question has been answered i believe in the official thread on Kodi forum search there if you still experience the problem open a separate support issue. https://forum.kodi.tv/showthread.php?tid=339798

**Comment by FunctionalHacker** [comment]
Yes I can't get any subtitles on any content. The subtitles work on the same content in the official app.

I understand that my information is not much to go on, but I wanted to reach out first to see if this is a known issue. I can file a proper bug ticket later this week.

**Comment by VadVoci** [comment]
If you use subtitles often, you may find that clicking on Subtitles > Subtitles Settings every time you start a video, can be a bit annoying.
I mean the plugin.video.hbogoeu application in this case.
Every time I start playing a movie in HgoGo, it automatically loads my subtitles, but in English, because it's the first in a list of four subtitles:
English- (external) (1/4)
Unknown-RON (external) (2/4)
English (3/4)
Romanian (4/4) 

I am interested in the option (4/4), respectively the Romanian subtitles, the last one in the list of choices. 
Could I configure, or could it be implemented in the future to be able to choose which option to have automatically?

I uploaded some sample photos :
1. https://i.imgur.com/MWNAwkx.jpg
2. https://i.imgur.com/gWvzwYa.jpg
3. https://i.imgur.com/VdJstGl.jpg
4. https://i.imgur.com/GzM90xC.jpg
5. https://i.imgur.com/zjNJcR7.jpg


Trying to set up a permanent choice of preferences does not seem to work .

**Comment by arvvoid** [comment]
Ok, waiting for the bug report with a full debug log.

The issue can be totally unrelated but take a look here as well https://github.com/arvvoid/plugin.video.hbogoeu/issues/116

**Comment by arvvoid** [comment]
Stalled closing. Please open a bug report with log if necessary.
