### ISSUE TITLE
HBO España (https://en.hboespana.com/) [WORK IN PROGRESS]

### ISSUE THREAD

**Issue by arvvoid** [arvvoid/plugin.video.hbogoeu#6]
It looks like it uses a different structure and api. Investigation and more info from someone local that uses it and have access id needed to evaluate the possibility of adding it to this add-on.

structure and api looks similar or the same to HBO Nordic #6

**Comment by arvvoid** [comment]
Supporting #6 and #7 would make it  a complete hbogo eu add-on

**Comment by sanangel** [comment]
Waiting anxiously for the development of Spain. Thank you...

**Comment by arvvoid** [comment]
After the current version get a little more testing and i make a stable release will start working on HBO Spain and Nordic. But I don't have a specific timeframe since I work on this every now and then when I have the time :) But contributions and pull requests are welcome.

**Comment by sanangel** [comment]
This is very happy news.
If you need a tester, I volunteer ...

**Comment by Sakerdot** [comment]
I can give it a go, have you started figuring out its api?

**Comment by arvvoid** [comment]
@Sakerdot Hello, no i havent started any work on this so all have to be figured out.
Login (direct and throu operators if there is 3th party logins for HBO Spain), Categories, Listings, Purchase.
 I just took a quick look from what i saw HBO Spain and Nordic are very similar, so those 2 regions probably share the same API (different domain names and servers tho).
Good luck with HBO Spain, as a bonus figuring that out will open the door for HBO Nordic as well.

**Comment by Sakerdot** [comment]
I've made some progress on this, I've managed to login and get some folders, I might create a pull request later today/next week.

**Comment by sanangel** [comment]
@Sakerdot if you need a tester, I'm your man ... I'm from Spain with a Spanish account (from Vodafone)

**Comment by sanangel** [comment]
@Sakerdot and @arvvoid 
I have installed the add-on and it works for me and with 1080 resolution.
I do not know how to express my gratitude for your work !!!!
Many thanks!!!!
If you need something, whatever is necessary, here you have me for whatever is necessary

**Comment by Tr1aX** [comment]
I'm also available for testing if needed. I have some IT background that maybe can be useful as well as a Spanish 2 months trial HBO account.

**Comment by Sakerdot** [comment]
@sanangel @Tr1aX the best thing right now would be to use the app and give all the feedback you can, anything weird you find, any errors that pop up, whatever.

I won't have much time for a while but once I do I'll implement all that is missing, and then a more thorough testing will be needed.

**Comment by sanangel** [comment]
I've been testing the application and I've seen several chapters and, so far, it's going very well. It is fast to load and play without problems. In my case, in a Mecool K1 Pro with Coreelec and 1080 quality. The only "problems" found: the audio is stereo, there is no 5.1 option and the menus and names of the series and movies are in English instead of in Spanish. But you can live without that after having HBO in Kodi ...

**Comment by Tr1aX** [comment]
I've tested a bit in a raspberry pi and Libreelec and so far so good. Addon and all dependencies installed from zip without any problem and Widevine later when tried to watch the first stream. But after Widevine installation i had to reboot libreelec in order to be able to load the streams. Other than that I've also found that the audio channel preferences doesn't remain saved as everytime the streams begin in English and I have to switch to Spanish. Playback in 1080p is perfect though, 0 problems. Thank you very much arvvoid!!
@sanangel haven't you got the DD+ audio channel? I think that one is 5.1.

**Comment by Tr1aX** [comment]
Ah, and menu titles are also in English in my case.

**Comment by arvvoid** [comment]
Hello, the content is retrieved in English only in the Spanish handler atm, I'm sure that will get improved when Sakerdot gets some free time to work on it.

For default audio and subtitle language; that's a global Kodi settings, Go to settings>appearance>international and set your prefered audio and/or subtitle stream there.
If DD+ is listed in the available audio streams than yes thats 5.1, maybe it's available for your region idk, for the hbogo.eu region only 2.0 is available.

**Comment by arvvoid** [comment]
@sanangel @Tr1aX does subtitles work for you?

**Comment by sanangel** [comment]
No, there are no subtitles.
And the audio language, I confirm that for me is 2.0

**Comment by arvvoid** [comment]
@sanangel @Tr1aX  New test version is available in pull request please test an report back.

From now on all discussion and reports regarding HBO Spain should be done on the pull request. This conversation will be closed. So we keep all in one place.

GO TO: https://github.com/arvvoid/plugin.video.hbogoeu/pull/13
