### ISSUE TITLE
HBO Nordic (https://www.hbonordic.com/) [WORK IN PROGRESS]

### ISSUE THREAD

**Issue by arvvoid** [arvvoid/plugin.video.hbogoeu#7]
It looks like it uses a different structure and api. Investigation and more info from someone local that uses it and have access id needed to evaluate the possibility of adding it to this add-on.

structure and api looks similar or the same to HBO España #6

**Comment by arvvoid** [comment]
Supporting #6 and #7 would make it  a complete hbogo eu add-on

**Comment by macardi** [comment]
I have a subscription for HBO Nordic, and could assist with testing.

**Comment by arvvoid** [comment]
Hello,

i suspect the Nordic api is identical to the Spanish one currently in development by @Sakerdot.

The only way to know is to try: 
[plugin.video.hbogoeu-nordicex.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3062274/plugin.video.hbogoeu-nordicex.zip) this is a quick and dirty test version with basic functionality. Select HBO Nordic (experimental) during setup, enter your credentials and report results pls.

**Comment by macardi** [comment]
Hi, will test tonight when home from work, and report back.

**Comment by macardi** [comment]
Hi, I have done some testing. At first I was not able to login. But after looking at the code in handlersp.py I changed every instance of "https://api-hboe........" to "https://api-hbon......" (e for Espania, and n for Nordic i guess) and after that it worked. During my first run i got a lot of errors when choosing a category, movie, episode etc, but after a second run those errors went away. Some labels and artwork in various lists and other views are missing, but It seems to be somewhat related to the skin Im using since the standard skin at least shows labels in every list but missing other info (maybe movie and episode info is not supported by the addon?), . Another thing I have noticed is that II only got 2.0 sound. 

However, this is really great and I guess your right concerning Nordic and Spain share the same api. Sadly I have no knowledge concerning python or coding in general so I cant assist with further development, but Im love to help out in whatever other way i can. 

A big thanks for doing this and share it with the community , a HBO addon is really the last missing piece of my Kodi setup so Im really grateful for your work.

**Comment by arvvoid** [comment]
Hello,

@marcadi tnx for reporting, knowing that is useful information. This is just an initial experimental version the handler for spain and nordic will get polished and improved over time :)
For sound 2.0 is what we get for the other regions as well that's blocked on hbo go side so nothing we can do about it, they provide 5.1 only on certain certified devices (not in web browser mode).

Here is the fixed hbo go Nordic test version until this is properly merged and released in the standard release: 
[plugin.video.hbogoeu-nordicex.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3067193/plugin.video.hbogoeu-nordicex.zip)
 
Can you send me a full debug log done with this version (perform some actions, browse, play something, ecc and then submit . a debug log)

**Comment by macardi** [comment]
Did some browsing and played some episodes/movies with your new version. 
Debug log: https://paste.ubuntu.com/p/vWVkHx9PBd/
I got some errors when trying to play some files (seems random) the same movie/episode works at another session or starts playing after a number of attempts.

**Comment by arvvoid** [comment]
Tnx for the log will be useful.
Can't find anything useful for the random errors, but we will see if this still happens when the login procedure get improved to have a persistent session, to not login on each action like is now.

**Comment by macardi** [comment]
Also subtitles does not work. Is that because this is an experimental version or is this not supported by the addon?

**Comment by arvvoid** [comment]
Subtitles are supported an should work. Subtitles are handled by inputstream.adaptive. If you go to the subtitle menu during playback are subtitles shown there? If you enable them and select a language are the subtitles shown at all or shown incorrectly?

**Comment by macardi** [comment]
Hi, There are no subtitles available in that menu. The option to choose between subtitles is grayed out and it says "Subtitles: None". Is it a setting I have to enable in inputstream.adaptive? Subtitles works in other similar addons such as Netflix and Viaplay that also depends on imputstream.adaptive.

**Comment by PolliSoft** [comment]
Hi, I just found this and downloaded the Nordic test version. Let me know if you want some log or other info.
I'm running a Windows 10 64bit PC, with Kodi 18.2 RC1 64bit.

**Comment by arvvoid** [comment]
@macardi ok, might be the subtitles are missing from the manifest and have to be handled differently will look into it. Tnx for reporting. 
@PolliSoft just try it out and report any issue found with full debug logs :)

**Comment by arvvoid** [comment]
@macardi @PolliSoft  New test version is available in pull request please test an report back.

From now on all discussion and reports regarding HBO Nordic should be done on the pull request. This conversation will be closed. So we keep all in one place.

GO TO: https://github.com/arvvoid/plugin.video.hbogoeu/pull/13
